= LinkML Antora generator

Generates an Antora module from a LinkML schema.

The generated module can then be made part of an Antora component version, playing its part in a larger piece of documentation.

== Why not regular AsciiDoc?

Whichever choice is made, it is relatively easy to add or remove Antora-specific assumptions through post-processing, so it's not really important. The reason why Antora was chosen is because it helps organising the files in a standardized way, but moreover the module can be put to use immediately as part of an Antora-based site.




== Mapping

* LinkML schema -> Antora module
** LinkML class -> Antora page (class template)
*** LinkML class attributes -> Antora page section
** LinkML enumeration -> Antora page (enum template)
** LinkML type -> Antora page (type template; _TODO_)
** LinkML slots -> Antora page (_out of scope for now_)

== Limitations

* Non-attribute (top-level) slots are out of scope for now.

== If Antora is not desired

Currently, the generator is tightly coupled to Antora. If one wishes to use the generated AsciiDoc outside of the Antora framework, the following post-processing should suffice:

* Cross-references (`xref`) must be transformed such that they no longer use Antora-specific resource IDs. In many cases, however, these IDs are already compatible with regular relative paths.
* The output directory follows Antora's convention regarding how to structure documentation in so called component versions. This is structure should work fine without using Antora as well, but one might desire a different structure. If you change the directory structure, however, you also need to update all the includes and cross-references.

This is just what comes to mind immediately. More steps may be needed.

NOTE: In future releases it may become configurable whether the output is an Antora component or generic AsciiDoc.

== Benefits over alternatives

* Server-sided diagram rendering.
** Avoids diagram code to match search queries and appear in search results.
** Users never see diagram code when rendering has not finished yet.
** No reliance on external services for availability of diagrams.
** Avoids complicated architectures and keeps the website static and easy to work with.
* AsciiDoc partials generation for maximal reusability of documentation parts.

== Development

////
Perhaps not.

=== Conventions

* I emphasize the use of hashable, immutable data types, and try to make everything deterministic using only data types that support ordering.
* If methods or functions start with a verb they have side effects (_pull_ or _push_). Otherwise, they are pure functions (_transformations_).
* Typenames are `UpperCamelCase` and try to encode a lot of context, whereas function names are `lower_snake_case` and are contextualized by their namespace.
** For example, the type `AntoraPage` is not abbreviated to just `Page` even though the namespace is `antora`.
////
